version: "3.8"
services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=212223
    ports:
      - "3306:3306"
    volumes:
      - myData:/var/lib/mysql/
volumes:
  myData:
    name: 'myData'